name = "CATSExpand"
uuid = "2f3e339c-8e95-4fd8-9255-42e559e5e09b"
version = "0.1.0"
authors = ["CATSExpand developers"]

[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"

[compat]
AxisKeys = "0.2.17"
BenchmarkTools = "1.6.3"
CSV = "0.10.15"
DataFrames = "1.8.1"
DataStructures = "0.19.3"
Infiltrator = "1.9.4"
JuMP = "1.29.3"
Mosek = "11.0.1"
MosekTools = "0.15.10"
NamedArrays = "0.10.5"
ProgressBars = "1.5.1"
Revise = "3.12.2"
Tables = "1.12.1"
TensorCast = "0.4.4"
