name = "CATEX"
uuid = "2f3e339c-8e95-4fd8-9255-42e559e5e09b"
version = "0.1.0"
authors = ["CATEX developers"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
Infiltrator = "1.9.4"
JuMP = "1.29.3"
Mosek = "11.0.1"
MosekTools = "0.15.10"
NamedArrays = "0.10.5"
Tables = "1.12.1"
